include ../common/Makefile.def

TARGET = boost-unit-test$(EXE)

SOURCES = \
    src/example.cpp \
    src/main.cpp

INCLUDE= -I$(HOME)/binary/boost/include
LIB= -L$(HOME)/binary/boost/lib

CXX_FLAGS += 

include ../common/Makefile.in
